/*
 * Otto notification service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/danielmunro/otto-notification-service/internal"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	router := internal.NewRouter()

	log.Fatal(http.ListenAndServe(":8083", router))
}
